### ISSUE TITLE
Bump kernel version to something more modern

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcushubos#13]
meta-yocto-bsp pulls in 4.19.14, which is from this year, but isn't especially recent. we should be able to upgrade to 4.19.78 (I'm now using this on many different hubs), but I can't find a clean way to update without modifying the files in poky:

```
$ git diff poky/meta-yocto-bsp/recipes-kernel/linux/linux-yocto_4.19.bbappend
diff --git a/poky/meta-yocto-bsp/recipes-kernel/linux/linux-yocto_4.19.bbappend b/poky/meta-yocto-bsp/recipes-kernel/linux/linux-yocto_4.19.bbappend
index 6025230c..cb30b4d5 100644
--- a/poky/meta-yocto-bsp/recipes-kernel/linux/linux-yocto_4.19.bbappend
+++ b/poky/meta-yocto-bsp/recipes-kernel/linux/linux-yocto_4.19.bbappend
@@ -11,7 +11,7 @@ KMACHINE_beaglebone-yocto ?= "beaglebone"
 SRCREV_machine_genericx86    ?= "11e0e616ed095bb8012e1b4a231254c9656a0193"
 SRCREV_machine_genericx86-64 ?= "11e0e616ed095bb8012e1b4a231254c9656a0193"
 SRCREV_machine_edgerouter ?= "eebb51300a07804a020ec468b5f8c5bf720198d9"
-SRCREV_machine_beaglebone-yocto ?= "eebb51300a07804a020ec468b5f8c5bf720198d9"
+SRCREV_machine_beaglebone-yocto ?= "a915fbeae8ed987402f69666d90bef15a01c5823"
 SRCREV_machine_mpc8315e-rdb ?= "8b60f968823256f5d2889c4520d70299ca21411b"
 
 COMPATIBLE_MACHINE_genericx86 = "genericx86"
@@ -23,5 +23,5 @@ COMPATIBLE_MACHINE_mpc8315e-rdb = "mpc8315e-rdb"
 LINUX_VERSION_genericx86 = "4.19.19"
 LINUX_VERSION_genericx86-64 = "4.19.19"
 LINUX_VERSION_edgerouter = "4.19.14"
-LINUX_VERSION_beaglebone-yocto = "4.19.14"
+LINUX_VERSION_beaglebone-yocto = "4.19.78"
 LINUX_VERSION_mpc8315e-rdb = "4.19.14"
```

**Comment by pcouto64** [comment]
As you may have noticed, I did clean up _all_ the changes to poky and the other open-source meta-xxx repos over the weekend.  This should be something we can change with just mods to the recipe append files in meta-iris.  In the past, I normally would keep things in line with the Yocto release just because that was the kernel with the most mileage on it.  Also, I would keep the v3 and the v2 kernels as close together in version as possible.  The v3 kernel is further behind now, but I don't see a point to upgrade it if folks do not have this hardware since it will likely take more of an effort than another bump of the beaglebone variant which is using the Yocto one rather than an older FSL community one.

**Comment by pcouto64** [comment]
Forced to 4.19.78 for TI build for now.  Will have to remember to remove this change on the next Yocto upgrade if the kernel has been updated to an even newer 4.x version.

**Comment by AndrewX192** [comment]
Thanks! I did notice that the yocto project uses a more modern kernel for 2.7.1, but meta-yocto-bsp uses this relatively old version instead. It looks like that only gets bumped 1-2x a year, which isn't great from a security standpoint. I assume someone is doing more device testing at that point, but if we're only upgrading minor LTS releases I don't feel like it's too big of an issue.
